# 1d filter

In [1]:
import torch
from torch.autograd import Variable
from torch.nn import Conv1d, Sequential, Module
from torch.optim import Adam, SGD

In [2]:
torch.cuda.is_available()

True

## building a convolutional network 

1D CNN; filter has fixed weights generated by fortran code

In [40]:
chanl_in = 1 # n_loc
chanl_out = 10 # n_loc
# thus our filter size is 1x10x10
# filter = a_filter -> returned by fortran code

class Net(Module):
    def __init__(self):
        super(Net, self).__init__() 

        self.cnn_layers = Sequential(
            Conv1d(chanl_in,chanl_out, kernel_size=7,bias=False)
        )

    def forward(self, x):
        x = self.cnn_layers(x)
        x = x.view(x.size(0), -1)
        return x

In [41]:
torch.random.manual_seed(42)
net = Net()

input = torch.randn(1, 1, 10)


In [43]:
input = torch.ones(12, 1, 10)
weights_layer1 = net.cnn_layers[0].weight.data
print(weights_layer1)
print(weights_layer1.shape)
output = net(input)
print(input)
print(output)
print(weights_layer1[:,:,0])
print(input.shape)
print(output.shape)

tensor([[[ 0.2890,  0.3137, -0.0885,  0.3472, -0.0828,  0.0763, -0.1840]],

        [[ 0.2220,  0.3332, -0.2773,  0.3285,  0.0707,  0.2792,  0.0512]],

        [[ 0.1822, -0.0534,  0.2914,  0.0559, -0.1764,  0.0963, -0.1741]],

        [[-0.0443, -0.1535,  0.2507, -0.2984, -0.1742, -0.1067, -0.2273]],

        [[ 0.0357, -0.3733,  0.3413, -0.3211,  0.2918,  0.0629, -0.1227]],

        [[ 0.2336,  0.0589,  0.3054,  0.0413, -0.1192,  0.1016, -0.1025]],

        [[ 0.1591,  0.3375,  0.2185, -0.1652,  0.2182,  0.0676,  0.1919]],

        [[-0.2304, -0.3742, -0.1460, -0.2899,  0.3101,  0.1089,  0.1566]],

        [[ 0.1195, -0.0066,  0.2958, -0.2685,  0.0238, -0.2580,  0.1165]],

        [[-0.1302,  0.1158, -0.0787,  0.3135, -0.2240, -0.2254, -0.2254]]])
torch.Size([10, 1, 7])
tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

     

In [10]:
import torch.nn as nn
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Sequential( 
                        nn.Conv1d(1, 10, 5), # layer1
                        nn.ReLU())
        self.conv2 = nn.Sequential(
                       nn.Conv2d(10, 4, 5), # layer2
                       nn.Sigmoid())

    def forward(self, x):
        x = self.conv1(x)
        return self.conv2(x)

In [11]:
model = Model()
weights_layer1 = model.conv1[0].weight.data # gets weights
bias_layer1 = model.conv1[0].bias.data # gets bias
weights_layer2 = model.conv2[0].weight.data
bias_layer2 = model.conv2[0].bias.data

In [12]:
print(weights_layer1)

tensor([[[[-0.1046, -0.1366, -0.1460, -0.1997,  0.1916],
          [-0.0780,  0.1427,  0.1885,  0.1805,  0.1439],
          [ 0.1106, -0.1603,  0.0782, -0.0258,  0.0378],
          [ 0.0158,  0.0701,  0.0895,  0.1202,  0.0768],
          [ 0.1853, -0.1200,  0.0739,  0.0320, -0.0553]]],


        [[[ 0.0601, -0.0608,  0.1187,  0.1572, -0.1100],
          [ 0.1423,  0.0539,  0.0793,  0.1080,  0.0103],
          [-0.0223, -0.0622,  0.0910, -0.0497,  0.0365],
          [-0.1323,  0.0813, -0.0198, -0.1515,  0.1989],
          [ 0.0090, -0.0420,  0.0278, -0.0127,  0.1119]]],


        [[[ 0.0246, -0.0263, -0.1701, -0.0424, -0.0364],
          [ 0.1188,  0.1074,  0.1133,  0.1900, -0.0446],
          [ 0.1270, -0.0677,  0.0932,  0.0298,  0.1894],
          [-0.1926,  0.0753,  0.0453,  0.1944, -0.0063],
          [-0.0287,  0.0822, -0.1902, -0.0052, -0.1631]]],


        [[[-0.0190, -0.0729, -0.1857,  0.1380,  0.1343],
          [ 0.0229,  0.0517, -0.0449, -0.1380, -0.1816],
          [-0.1221,